---
title: "Random notes"

engine: knitr 

execute:
    eval: false

format:
    html:
        link-external-icon: true
        link-external-newwindow: true
        css: config/styles.css
        toc: true
        embed-resources: true
        theme: cosmo

filters:
    - config/italics-denovo.lua
    - config/links.lua

bibliography: config/references.bib
---



## Area for ideas and questions

Questions:

-   Do the students know about strandedness? If no, consider incorporating a subquestion in Qst 2
-   I asked the students to generate a project dir in ~/personal is that where they usually analyse the data or should I direct them elsewhere?
- Have students already used for-loops in slurm?
- Will the students be able to generate a slurm array? 
- Do students know how to use variables in bash code?


Thoughts/To-Do:

- Have a few shorter plenary sessions to also address qsts
- give html with code at around 3pm
- slurm arrays, not used yet but loops have been used --> plenary on this?
- explain things like `SAMPLE=$(cut -f1 metadata.txt | sed "1d" | sed -n "${SLURM_ARRAY_TASK_ID}p")`

Canvas,

-  Files that mirror the modules and where I can put the files and make them public in the modules 
-  Give also papers

Considerations to add some more hands-on practice in day 1:

-   Look into tools to assess strandedness (since plenty of studies don't provide that information)
-   Contamination screening with tools like kraken2 or fastq-screen
-   jellyfish to look at k-mer spectra
-   Assembly Tool comparison: RNAspades
-   Explore published genome \<---\> reads mapped to it in IGV

Notes on cleanup for the case that the tutorial should be rerun for testing:

```{bash}
rm trinity_mapping.txt logs/*
rm -r annotations/ fastp/ quality/ trinity/
```

:::

## Trinity conda issue

Trinity original:

- conda activate trinity_2.15.2
- numpy                     2.2.4           py313h17eae1a_0    conda-forge
- perl                      5.32.1          7_hd590300_perl5    conda-forge
- python                    3.13.2          hf636f53_101_cp313    conda-forge
- salmon                    1.10.3               haf24da9_3    bioconda

Trinity bbda env:

- conda activate transcriptomics_bbda
- numpy                     2.2.6           py310hefbff90_0    conda-forge
- perl                      5.32.1          7_hd590300_perl5    conda-forge
- python                    3.10.15         h4a871b0_2_cpython    conda-forge
- salmon                    1.10.3               haf24da9_3    bioconda


```{bash}
scp crunchomics:/zfs/omics/projects/education/BBDA_transcriptomics/denovo/trinity/trinity.Trinity* results/trinity 

rsync -av --prune-empty-dirs \
    --include='*/' \
    --include='quant.sf' \
    --include='quant.sf.genes' \
    --exclude='*' \
    crunchomics://zfs/omics/projects/education/BBDA_transcriptomics/denovo/trinity/salmon_abund/ results/trinity/salmon_abund/
```

```{r}
# Get a list of the salmon folder names
dir <- "results/trinity/salmon_abund"
folders <- list.dirs(dir, full.names = FALSE, recursive = FALSE)

# Using the folder names, extract the names of the treatments and build a samples dataframe
condition <- ifelse(grepl("^treated", folders), "treated", "untreated")

samples <- data.frame(
    run = folders,
    condition = factor(condition)
)

samples
```